### ISSUE TITLE
working on same network except in different network

### ISSUE THREAD

**Issue by rafattouqir** [Ankit-Aggarwal/SwiftyWebRTC#3]
I've used your implementation, It's working great in same network but when it comes to different network it' not connecting, may be ice candidate were not adding at proper time.

Need help or suggestion?

**Comment by Ankit-Aggarwal** [comment]
Some things to check : 
 - Your TURN AND STUN server are configured and working properly since if they are at different network these servers will be required to establish a connection.
- You need to add ICE candidate after adding remote sdp, if you have some candidate before that.. keep them in an array to be added when you gets remote sdp.

**Comment by rafattouqir** [comment]
I'm doing the same like caching remote candidates until remotesdp is set, but not working.

Is there any sample code that you could provide ? That would be great :)

**Comment by rafattouqir** [comment]
All of your implementation was ok, I was not sending ice candidates to remote properly.
You can close the issue.
